/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szemelyiazonositogui;

/**
 *
 * @author Tanulo
 */
public class szemelyiazonositogui extends javax.swing.JFrame {
        int osszeg = 0;
        int ev;
        String evszoveg = "";
        String bekertadat2;
        
    public szemelyiazonositogui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bekertadat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gombbevitel = new javax.swing.JButton();
        kiiras = new javax.swing.JLabel();
        gombreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Személyi azonosító");
        setResizable(false);

        bekertadat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bekertadatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Személyi azonosító ellenőrzése");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Kérem adja meg az azonosítót!: ");

        gombbevitel.setText("OK");
        gombbevitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gombbevitelActionPerformed(evt);
            }
        });

        kiiras.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N

        gombreset.setText("RESET");
        gombreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gombresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kiiras, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bekertadat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gombbevitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gombreset))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bekertadat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gombbevitel)
                    .addComponent(gombreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kiiras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bekertadatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bekertadatActionPerformed
        
    }//GEN-LAST:event_bekertadatActionPerformed

    private void gombbevitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gombbevitelActionPerformed
        bekertadat2 = bekertadat.getText();
        int eu2000 = Character.getNumericValue(bekertadat2.charAt(0));
        for (int i = 1; i < 3; i++) { //az ev utolso 2 szamjegyenek meghatarozasa
            evszoveg = evszoveg + Character.toString(bekertadat2.charAt(i));
        }
        ev = Integer.parseInt(evszoveg);
        
        for (int i = 0; i < 10; i++) { //a bekert adat feldarabolasa, tombbe toltese es az ellenorzo szamhoz szukseges ertek meghatarozasa
            if(ev < 97 && eu2000 < 3 || ev < 97 && eu2000 > 4){                   
                    osszeg = osszeg + (Character.getNumericValue(bekertadat2.charAt(i))*(i+1));                
            }else{               
                    osszeg = osszeg + (Character.getNumericValue(bekertadat2.charAt(i))*(10-i));               
            }
        }
        if(osszeg % 11 == Character.getNumericValue(bekertadat2.charAt(10))){
            kiiras.setText("Helyes!");
        }else{
            kiiras.setText("Helytelen!");
        }
        osszeg = 0;
        evszoveg = "";
    }//GEN-LAST:event_gombbevitelActionPerformed

    private void gombresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gombresetActionPerformed
        bekertadat.setText("");
        kiiras.setText("");
    }//GEN-LAST:event_gombresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(szemelyiazonositogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(szemelyiazonositogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(szemelyiazonositogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(szemelyiazonositogui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new szemelyiazonositogui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bekertadat;
    private javax.swing.JButton gombbevitel;
    private javax.swing.JButton gombreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kiiras;
    // End of variables declaration//GEN-END:variables
}
